# -*- coding: utf-8 -*-

CONFIG_FILE = 'site.yaml'

IMAGE_SUFFIX_LIST = ['gif', 'jpg', 'jpeg', 'png']
FONT_SUFFIX_LIST = ['ttf', 'woff', 'woff2']

AJAX_PREFIX = 'ajax_'
PID_FN = '.pid'

KEY_ABSTRACT = 'abstract'
KEY_AUTHORS = 'authors'
KEY_BLOG = 'blog'
KEY_CODE = 'code'
KEY_CONTENT = 'content'
KEY_CWD = 'cwd'
KEY_DOMAIN = 'domain'
KEY_EMAIL = 'email'
KEY_FIGURE= 'fig'
KEY_FIRSTNAME = 'firstname'
KEY_FONTS = 'fonts'
KEY_FORMULA = 'formula'
KEY_GITHUB = 'github'
KEY_HTML = 'html'
KEY_HOSTNAME = 'hostname'
KEY_IGNORE = 'ignore'
KEY_IMAGES = 'images'
KEY_JINJA = 'jinja'
KEY_LANGUAGE = 'language'
KEY_LASTNAME = 'lastname'
KEY_LIBRARIES = 'libraries'
KEY_LOG = 'log'
KEY_MARKDOWN = 'md'
KEY_MATH = 'math'
KEY_OUT = 'out'
KEY_PORT = 'port'
KEY_PROJECT = 'project'
KEY_RECIPE = 'recipe'
KEY_RELEASE = 'release'
KEY_ROOT = 'root'
KEY_SCRIPTS = 'scripts'
KEY_SERVER = 'server'
KEY_SRC = 'src'
KEY_STYLES = 'styles'
KEY_SUBTITLE = 'subtitle'
KEY_TAGS = 'tags'
KEY_TEMPLATE = 'template'
KEY_TEMPLATES = 'templates'
KEY_TIMER = 'timer'
KEY_TITLE = 'title'
KEY_UPDATE = 'update'
KEY_VERSION = 'version'
KEY_VIDEO = 'vid'
KEY_VOCABULARY = 'vocabulary'
